const ALL_MESSAGES: { [c: string]: string } = {
  '000000': 'Thực hiện thành công',
  '000001': 'Yêu cầu đã được chấp nhận và đang trong quá trình xử lý.',
  '000002': 'Không có thông tin về gói đang thêm mới hoặc sửa thành công.',
  '000003':
    'Yêu cầu tải RBT được chấp nhận và RBTs sẽ được tải về sau khi thuê bao đăng kí dịch vụ RBT.',
  '100001': 'Lỗi không xác đinh.',
  '100002': 'Hệ thống đang bận xử lý.',
  '100003': 'Thời gian chờ đợi xử lý đã hết.',
  '100004': 'Lỗi đường truyền.',
  '100005': 'Lỗi xử lý database.',
  '100006': 'Lỗi xử lý database.',
  '100007': 'Dịch vụ tạm dừng hoạt động.',
  '100008': 'Lỗi thực thi cơ sở dữ liệu.',
  '200001': 'Không vào giá trị các tham số bắt buộc.',
  '200002': 'Dữ liệu nhập vào không hợp lệ.',
  '200003': 'Độ dài tham số vượt quá độ dài cho phép.',
  '200004': 'Tất cả các tham số vào đều rỗng(null).',
  '200005':
    'Sai định dạng thời gian của RBT hoặc thời gian bắt đầu phải bé hơn thời gian kết thúc.',
  '200006': 'Vào giá trị của những tham số không yêu cầu.',
  '201001': 'Sai định dạng số điện thoại.',
  '201002': 'Sai mật khẩu.',
  '201003': 'Không vào mật khẩu.',
  '202001': 'Sai định dạng của hộp âm nhạc.',
  '202002': 'Sai định dạng của mã RBT.',
  '300001': 'Vượt quá số lượng thành viên cho phép.',
  '300002': 'Không lấy được thông tin.',
  '301001': 'Thuê bao không tồn tại.',
  '301002': 'Thuê bao đã đăng ký dịch vụ trước đó.',
  '301003': 'Sai mật khẩu.',
  '301004': 'Không gửi được tin nhắn đến thuê bao.',
  '301005': 'Vào sai mã kiểm tra.',
  '301006': 'Thuê bao đang chờ đăng ký hoặc chờ được kích hoạt.',
  '301008': 'Không lấy được mã kiểm tra do thuê bao có lỗi.',
  '301009': 'Không được phép định nghĩa thuê bao do thuê bao đang có lỗi.',
  '301010': 'Không xóa được thuê bao do thuê bao đang có lỗi.',
  '301011': 'Thuê bao nợ tiền.',
  '301012': 'Mã kiểm tra không tồn tại.',
  '301013': 'Không thể tải về trang thái dịch vụ thuê bao.',
  '301014': 'Không thể thiết lập trạng thái dịch vụ thuê bao',
  '301015': 'Dịch vụ không đáp ứng cho thuê bao do lỗi trạng thái dịch vụ của thuê bao.',
  '301016': 'Thuê bao không cho phép các thuê bao khác sao chép RBTs.',
  '301017': 'Không thể sao chép cấu hình hệ thống.',
  '301018': 'Số điện thoại của thuê bao bị sao chép không tồn tại.',
  '301019': 'Danh sách các RBT có chứa RBT không hợp lệ (trạng thái không xác định).',
  '301020': 'RBT không thuộc một công ty nào.',
  '301021': 'Đối tượng bị hạn chế lần tiêu thụ.',
  '301022': 'Mã giới hạn tiêu dùng không tồn tại.',
  '301023': 'Vượt quá giới hạn sử dụng.',
  '301024': 'Loại RBT không tồn tại.',
  '301025': 'Hệ thống tính tiền mới không thay đổi so với hệ thống cũ nên không cần thay đổi gì.',
  '309123': 'Số lần thuê bao đăng ký dịch vụ trong ngày đã vượt quá giới hạn.',
  '301026': 'Một nhánh dịch vụ mới không thay đổi gì so với dịch vụ cũ.',
  '301027': 'Mã ngôn ngữ không được Hệ thống hỗ trợ.',
  '301029': 'Số thuê bao không thuộc phạm vi vùng.',
  '302001': 'Nhạc chờ đã tồn tại trong BST!',
  '302002': 'Lỗi truyền file RBT.',
  '302003': 'Nhạc chờ không tồn tại.',
  '302004': 'RBT đã bị yêu cầu xóa.',
  '302005': 'RBT của CP yêu cầu xử lý không thuộc về CP đó.',
  '302006': 'RBT đã được yêu cầu sửa chữa.',
  '302007': 'Số lượng kết quả truy vấn bằng 0.',
  '302008': 'RBT đang trong trạng thái được thay đổi.',
  '302009': 'RBT trong thư để tải lên có lỗi.',
  '302010': 'Lỗi tính cước thuê bao.',
  '302011': 'Nhạc chờ đã có trong bộ sưu tập',
  '302015': 'RBT đã ở trạng thái ẩn (chưa kích hoạt).',
  '302016': 'RBT đã ở trạng thái được phép hiển thị.',
  '302017': 'Hộp âm nhạc không tồn tại.',
  '302018': 'RBT chưa được tải về.',
  '302019': 'RBT hết hạn sử dụng.',
  '302020': 'Số lượng RBT trong hộp âm nhạc vượt quá giới hạn.',
  '302021': 'Kiểu thư mục không tồn tại.',
  '302022': 'Mã xác định trong của thư mục không tồn tại.',
  '302023': 'Không tạo được thư mục.',
  '302026': 'Không ẩn được trạng thái của RBT.',
  '302027': 'Không hiện được trạng thái của RBT.',
  '302028': 'RBT đang đợi được chấp nhận.',
  '302029':
    'Lỗi sai thời hạn sử dụng RBT: Thời gian sử dụng lại đặt trước thời gian hiện thời hoặc Thời hạn sử dụng sai (bắt đầu và kết thúc)',
  '302030': 'Thời gian chơi RBT bị đè lên nhau.',
  '302031': 'Mã kiểu thư mục không tồn tại hoặc sai định dạng.',
  '302032': 'Cấu trúc thư mục sai và không chứa được RBT.',
  '302033': 'Thư mục gốc không được chứa RBT (hệ thống chỉ cho phép thư mục con chứa RBT)',
  '302034': 'Không được xóa thư mục chứa RBT.',
  '302035': 'Không xóa được thư mục chứa thư mục con.',
  '302037': 'Không sao chép được tất cả RBTs trong thư mục.',
  '302038': 'Không sao chép được một vài RBTs trong thư mục.',
  '302039':
    'Các trường đợi được chấp nhận không thể sửa chữa. Các trường đang ở trong trạng thái bị xóa.',
  '302040': 'Ngôn ngữ không tồn tại.',
  '302041': 'Công ty không tồn tại.',
  '302042': 'Mã vùng không tồn tại.',
  '302043': 'Sai định dạng file.',
  '302044': 'Không ẩn được bài hát trong hộp âm nhạc.',
  '302045': 'Không thể thay đổi thuộc tính tài nguyên của thư mục.',
  '302046': 'Thư mục mẹ không tồn tại.',
  '302047': 'Thư mục RBT không tồn tại.',
  '302048': 'Hộp âm nhạc đã tồn tại.',
  '302052': 'Hộp âm nhạc quá hạn.',
  '302053': 'Hộp âm nhạc đang trọng trạng thái chờ được chấp nhận.',
  '302054': 'Không ẩn được trạng thái hiện thời của hộp âm nhạc.',
  '302055': 'Không hiển thị được trạng thái hiện thời của hộp âm nhạc.',
  '302056': 'Thư mục chứa RBT không tồn tại.',
  '302057': 'Thư mục chứa RBT đang đợi được chấp nhận.',
  '302058': 'Không ẩn được trạng thái hiện thời của thư mục chứa RBT.',
  '302059': 'Không hiển thị được trạng thái hiện thời của thư mục RBT.',
  '302060': 'Không thực hiện thay đổi một chuỗi RBT.',
  '302061': 'Không thực hiện được thay đổi chuỗi',
  '302065': 'Ngày hết hạn sử dụng của hôm âm nhạc sớm hơn ngày hiện thời.',
  '302066': 'Hộp âm nhạc đang đợi được chấp nhận đã bị xóa nên không thể thay đổi được.',
  '302067': 'Hộp âm nhạc không thể thay đổi.',
  '302068': 'RBT không thuộc một danh sách RBTs nào cả.',
  '302069': 'Tất cả RBTs đã bao gồm trong danh sách RBT.',
  '302070': 'Không lấy được thư mục hoạt động của file announcement trong hộp âm nhạc.',
  '302071': 'Đã tồn tại cả hai trường ghi người gọi và nhận.',
  '302072': 'Không tồn tại cả hai trường ghi người gọi và nhận.',
  '302073': 'Thuê bao hoặc tài nguyên RBT không tồn tại.',
  '302074': 'RBT không thể được sửa chữa.',
  '302075': 'Số nhạc nền không tồn tại trong mục ghi cấu hình.',
  '302076': 'Âm nhạc nền không tồn tại.',
  '302078': 'Không soạn được RBT.',
  '302079': 'Số người gọi đã đặt trước đó.',
  '302080': 'Thời gian hiệu lực bị sai.',
  '302082': 'Vượt quá hạn sử dụng của hộp âm nhạc.',
  '302088': 'Thuê bao chưa tải RBT.',
  '302091': 'RBT và hộp âm nhạc  hết hạn sử dụng và không gia hạn được.',
  '302093': 'Hạn sử dụng của một gói sớm hơn thời gian hiện thời.',
  '302100': 'RBT đã tồn tại trước đó.',
  '302101': 'Announcement file không tồn tại.',
  '302102': 'Không sao chép được file announcement.',
  '302103': 'Mã trường ghi RBTs ngầm định không tồn tại.',
  '302104': 'Trạng thái hiện thời của gói RBT không ẩn được.',
  '302105': 'Trạng thái hiện thời của gói RBT không hiển thị được.',
  '302110': 'Ngày bắt đầu sớm hơn ngày kết thúc thời hạn sử dụng.',
  '302112': 'Sai lệch hạn sử dụng.',
  '302119': 'Trạng thái RBT bị lỗi.',
  '302123': 'RBT tồn tại trong thư viện cá nhân.',
  '302124': 'Kiểu RBT khác nhau.',
  '302125':
    'Kiểu RBT đặt không trùng với kiểu trong danh sách. Ví dụ kiểu RBT được đặt là PLUS RBT nhưng trong danh sách RBT lại là RBT thường.',
  '302133': 'Số lượng RBTs tải vượt quá tối đa cho phép',
  '303001': 'Thuê bao đã định nghĩa nhóm gọi đến (gồm cả tên và số thuê bao).',
  '303002': 'Khi sửa chữa hoặc xóa một nhóm người gọi, trường ghi nhận báo nhóm đó không tồn tại.',
  '303003': 'Nhóm người gọi không thể bổ xung bởi số người trong nhóm vượt quá giới hạn cho phép.',
  '303004': 'Nhóm người gọi bao gồm những thành viên không thể xóa được.',
  '303011': 'Thuê bao đã tồn tại trong nhóm.',
  '303012': 'Thuê bao không tồn tại trong nhóm.',
  '303013': 'Số thuê bao trong nhóm vượt quá giới hạn.',
  '303014': 'Không thể sửa được số của thuê bao bởi thuê bao này nằm trong nhóm khác.',
  '303015': 'Số lượng thuê bao gọi tới vượt quá giới hạn cho phép.',
  '303021': 'RBT đã tồn tại trong hộp âm nhạc.',
  '303023': 'Số lượng RBT được tải về vượt quá giới hạn cho phép.',
  '303024': 'Số lượng RBT vượt quá giới hạn cho phép.',
  '303025': 'Gói tải về không tồn tại.',
  '303028': 'Gói chuẩn bị tải về đã được tải trước đó.',
  '303029': 'Thuê bao không tải gói về.',
  '303030': 'Thuê bao không được phép tải nhiều gói của một CP.',
  '303031': 'Hộp âm nhạc đã tồn tại.',
  '303032': 'Hộp âm nhạc không tồn tại.',
  '303033': 'Chủ sở hữu của hộp âm nhạc không tồn tại.',
  '303041': 'RBT đã tồn tại trong hộp âm nhạc.',
  '303042': 'RBT không tồn tại trong hộp âm nhạc.',
  '303043': 'Nội dung của nhóm RBT không sửa chữa được.',
  '303051': 'Cài đặt RBT đã tồn tại.',
  '303052': 'Cài đặt cho RBT không tồn tại.',
  '303053': 'Nhóm hoặc bộ phận không tồn tại.',
  '303054': 'Tình trạng dịch vụ của nhóm hoặc bộ phận không bình thường',
  '303056': 'Nguồn RBT không nằm trong thư viện nhạc cá nhân của người sử dụng, mà sẽ được copied.',
  '303057': 'Thông tin cấu hình hệ thống thiết yếu không tồn tại',
  '304001': 'Không tìm thấy giá trị thống kê.',
  '306001': 'RBT ngầm định không tồn tại.',
  '306002': 'Hệ thống báo lỗi khi hiển thị mã RBT.',
  '306003': 'Hệ thống báo lỗi khi mã nhận dạng trong của RBT chuyển thành mã RBT.',
  '306004': 'Tham số vào sai.',
  '306012': 'Mã vùng không tồn tại.',
  '307016': 'Nhóm đã cài đặt rồi.',
  '307017': 'Dải số không tồn tại',
  '308001': 'Người nhận quà tặng RBT không đăng ký dịch vụ RBT',
  '308002': 'Số lượng RBT của người nhận quà tặng RBT đã vượt quá giới hạn cho phép.',
  '308003': 'Người nhận quà tặng không phải thuộc vùng thuê bao cho phép.',
  '308004': 'Người nhận quà tặng đã có quà tặng này trong nhóm rồi.',
  '308005': 'Số tháng tặng quà vượt quá giá trị cho phép.',
  '308006': 'Người nhận quà tặng dịch vụ RBT cũng đã đăng kí dịch vụ RBT.',
  '308007': 'Người được tặng không được là người tặng RBT',
  '308008': 'Dịch vụ hết hạn sử dụng.',
  '308009': 'Một phần của gói đang download bị lỗi!',
  '308010': 'Thuê bao đã có RBTs ngầm định, cài đặt không thực hiện được.',
  '308011': 'Một RBT không thể đặt được vào hộp âm nhạc.',
  '308012': 'RBT tồn tại trong danh sách RBT rồi.',
  '308013': 'Tải không thành công. Bạn đã có bài hát này hoặc bộ sưu tập của bạn đã đầy.',
  '308014': 'Lệnh gửi tặng bị lỗi.',
  '308015': 'Lệnh gửi tặng bị lỗi.',
  '308016': 'Thực hiện lệnh gửi tặng bị lỗi.',
  '308017': 'Thực hiện lệnh gửi tặng bị lỗi.',
  '308023': 'Bài hát (RBT) đã tồn tại hoặc đang được gửi tặng.',
  '309001': 'Vượt quá khả năng cung cấp của hệ thống.',
  '309002': 'Yêu cầu mã kiểm tra',
  '309003': 'Chính sách đăng ký không tìm thấy.',
  '309004': 'Không xóa và tạo được thuê bao tại website.',
  '309005': 'Chưa đặt kiểu truy cập',
  '309006': 'Số lượng thue bao định nghĩa trong ngày vượt quá giới hạn.',
  '309007': 'Không xóa hoặc tạo được thuê bao.',
  '309008': 'Thuê bao đang được tạo hoặc xóa.',
  '309113': 'Người dùng không dùng được dịch vụ RBT .',
  '309114': 'Thuê bao không thể xóa được.',
  '309115': 'Chưa đặt kiểu thuê bao.',
  '309116': 'Sai kiểu thuê bao hoặc kiểu truy cập.',
  '309117': 'Số lượng thuê bao hằng ngày dùng dịch vụ vượt quá giới hạn cho phép.',
  '309118': 'Thuê bao không được phép sử dụng dịch vụ dịch vụ RBT.',
  '309119': 'Vùng của thuê bao không được phép dùng dịch vụ.',
  '309120': 'Thời gian để tạo hoặc xóa một thuê bao nằm trong khoảng thời gian không cho phép.',
  '309121': 'Thuê bao thuộc nhóm khác.',
  '309122':
    'Tạo được dịch vụ cho thuê bao nhưng không gửi được tin nhắn SMS. Nhắc thuê bao để lấy mật khẩu qua Webiste.',
  '310001': 'Thuê bao không đủ tiền trong tài khoản.',
  '310010': 'Thuê bao không đủ tiền trong tài khoản.',
  '312003': 'Mã vùng không tồn tại.',
  '312004': 'Tài khoản của thuê bao không được phép thực hiện yêu cầu.',
  '312005': 'Mã không tồn tại.',
  '312008': 'Administrator không tồn tại.',
  '312009': 'Mã đăng nhập của tài khoản hệ thống đã tồn tại.',
  '312010': 'Mã đăng nhập của tài khoản hệ thống không tồn tại.',
  '312011': 'Mật khẩu cũ vào không đúng.',
  '312017': 'Quản trị không có quyền hoạt động trên thuê bao.',
  '313001': 'Mã trả về không tồn tại.',
  '313002': 'Dừng lại một vài tác vụ có lỗi.',
  '313003': 'Nhận lại một vài tác vụ có lỗi.',
  '313004': 'Sửa chưa các tác vụ tại thời điểm hoạt động bị lỗi.',
  '314001': 'Tên tham số không tồn tại.',
  '314002': 'Tên mới của biến không tuân theo yêu cầu đăng nhập.',
  '314003': 'Tham số cập nhật không tồn tại.',
  '314004': 'Kiểu tham số hàm gọi không tồn tại.',
  '314005': 'Lỗi xử lý database',
  '314006': 'Mục cấu hình đã tồn tại',
  '314007': 'Tham số vào không đúng hoặc không đúng với qui tắc cấu hình.',
  '314008': 'Hệ thống lỗi để cập nhật cấu hình',
  '315001': 'Danh sách xếp hạng không tồn tại',
  '315002': 'Vào vị trí của bảng xếp hạng sai.',
  '315003': 'Nội dung của một bảng xếp hạng bị sai.',
  '315004': 'Bảng xếp hạng bị trùng đè.',
  '315005': 'Bảng xếp hàng không thể bị xóa',
  '315006': 'Một vài RBTs có chung một vị trí trong bảng xếp hạng.',
  '315007': 'Một bảng xếp hạng có hiệu lực sớm hơn thời gian hiện tại.',
  '316001': 'Một phiên yêu cầu tồn tại.',
  '316002': 'Không có RBT tương ứng trong bảng xếp hạng.',
  '316003': 'Mã RBT không tồn tại.',
  '316004': 'RBT được kích hoạt không tồn tại hoặc ở trạng thái lỗi.',
  '317001': 'Thuê bao không yêu cầu dịch vụ.',
  '317002': 'Thuê bao bị lỗi không thể khởi tạo dịch vụ.',
  '317003': 'Thuê bao chưa kích hoạt dịch vụ thêm.',
  '317004': 'Thuê bao đang ở trạng thái lỗi và không thể hủy dịch vụ.',
  '317006': 'RBT không phải là RBT plus.',
  '317007': 'Bộ sưu tập cá nhân đã vượt quá mức cho phép',
  '317008': 'Thuê bao không được phép tải RBT – plus lên hệ thống.',
  '317010': 'Sau khi RBT plus được chấp thuận, RBT tải về lỗi.',
  '318004': 'Bạn không thể xóa hoặc sửa các trường đang đợi chấp thuận.',
  '319003': 'Luật không thể áp dùng cho dịch vụ thông tin.',
  '319004': 'Luật này không thể áp dụng cho hàm dịch vụ này.',
  '319005': 'Dịch vụ được yêu cầu nên không xóa được.',
  '319006': 'Dịch vụ chưa hoàn tất nên không thể tải về được.',
  '319008': 'Luật phí dịch vụ đã tồn tại.',
  '319009': 'Dịch vụ đã tồn tại',
  '319010': 'Luật cho dịch vụ đã tồn tại.',
  '319011': 'Dịch vụ không tồn tại hoặc đang bị ẩn.',
  '319012': 'Luật cho dịch vụ không tồn tại.',
  '319013': 'Chính sách thu tiền không tồn tại.',
  '319014': 'Mô tả của chính sách thu tiền không tồn tại.',
  '319015': 'Thuê bao không dùng dịch vụ không tồn tại.',
  '319016': 'Thuê bao dùng dịch vụ không tồn tại.',
  '319017': 'Thuê bao vừa yêu cầu dùng dịch vụ.',
  '319018': 'Chức năng này đưuợc yêu cầu lại.',
  '319019': 'Cờ thời gian khác nhau.',
  '319020': 'Chính sách thu tiền đã tồn tại.',
  '319021': 'Số lượng thuê bao yêu cầu dịch vụ vượt quá giới hạn.',
  '319022': 'Thuê bao không thể gọi dịch vụ do sô thuê bao không nằm trong dải số cho phép.',
  '320001': 'Thuê bao yêu cầu dịch vụ gọi đến.',
  '320002': 'Thuê bao không yêu cầu dịch vụ gọi đến.',
  '321001': 'Các cài đặt liên quan đến số thuê bao đã tồn tại.',
  '321002': 'Cài đặt RBT của thuê bao không tồn tại.',
};

const DEFAULT_MESSAGE = 'Hệ thống đang bận! Vui lòng thử lại sau!';
export function isSuccess(code: string) {
  return !!code && code[0] === '0';
}
export function getCrbtMessage(
  code: string,
  type?: 'addSubscribeReverse' | 'unSubscribeReverse'
): string | null {
  const msg: { [k: string]: { [c: string]: string } } = {
    addSubscribeReverse: {
      '301006': 'Đăng ký dịch vụ Reverse không thành công do đang sử dụng dịch vụ Reverse',
      '200002':
        'Đăng ký dịch vụ Reverse không thành công do gói cước thuê bao đang sử dụng không hợp lệ (Không phải gói tuần, ngày, plus)',
      '301001': 'Đăng ký dịch vụ Reverse không thành công do thuê bao chưa đăng ký CRBT',
      '301015':
        'Đăng ký dịch vụ Reverse không thành công do thuê bao đang ở trạng thái hủy dịch vụ CRBT',
    },
    unSubscribeReverse: {
      '301001':
        'Hủy dịch vụ Reverse không thành công do thuê bao chưa đăng ký dịch vụ CRBT hoặc Reverse',
      '301015':
        'Hủy dịch vụ Reverse không thành công do thuê bao đang ở trạng thái hủy dịch vụ CBRT',
    },
  };
  if (type) {
    return msg[type][code] ?? null;
  } else {
    return (
      (({
        '000000': 'Thực hiện thành công!',
        '301009': 'Đăng ký không thành công do đã đăng ký IMUZIK Plus',
        '310010': 'Đăng ký không thành công do tài khoản không đủ tiền',
        '301505': 'Đăng ký không thành công do thuê bao thuộc Blacklist hoặc Homephone',
        '100006': 'Đăng ký không thành công do lỗi kết nối hệ thống',
        '301006':
          'Đăng ký dịch vụ Nhạc chờ cá nhân không thành công do đang sử dụng dịch vụ Nhạc chờ cá nhân',
        '200002':
          'Đăng ký dịch vụ Nhạc chờ cá nhân không thành công do gói cước thuê bao đang sử dụng không hợp lệ (Không phải gói tuần, ngày, plus)',
        '301001': 'Thực hiện không thành công do thuê bao chưa đăng ký dịch vụ nhạc chờ',
        '301015': 'Thực hiện không thành công do thuê bao đang ở trạng thái hủy dịch vụ nhạc chờ',
      } as { [c: string]: string })[code] ||
        ALL_MESSAGES[code] ||
        DEFAULT_MESSAGE) ??
      null
    );
  }
}
