# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

def shared
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 5dmax
  pod 'google-cast-sdk'
  pod 'DateTools'
  pod 'Alamofire'
  pod 'Nuke'
  pod 'SnapKit'
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'MMDrawerController'
  pod 'WYPopoverController'
  pod 'Validator'
  pod 'Toast'
  pod 'SVPullToRefresh'
  pod 'TPKeyboardAvoiding'
#  pod 'FBSDKCoreKit'
#  pod 'FBSDKShareKit'
#  pod 'FBSDKLoginKit'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'EZYGradientView', :git => 'https://github.com/Niphery/EZYGradientView'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'RealmSwift', '~> 3.20.0'
#  pod 'PINRemoteImage'
  pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :branch => 'master'
  pod 'PINRemoteImage', :git => 'https://github.com/pinterest/PINRemoteImage', :branch => 'master'
  pod 'SwiftGifOrigin'
  pod 'Firebase/Messaging'
  pod 'NotificationBannerSwift', '2.0.1'
end

target '5dmax' do
  shared
  
end

target '5dmax - dev' do
  shared
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
