//
//  LocalizedString.swift
//  MyClip
//
//  Created by Huy Nguyen on 4/24/17.
//  Copyright © 2017 Huy Nguyen. All rights reserved.
//

import Foundation

extension String {
    static var okString: String { return RTLocalizationSystem.rtLocalize("dong_y", comment: "")}
    static var cancel: String { return RTLocalizationSystem.rtLocalize("huy", comment: "")}
    static var refuse: String { return RTLocalizationSystem.rtLocalize("tu_choi", comment: "")}
    static var ignore: String { return RTLocalizationSystem.rtLocalize("bo_qua", comment: "")}
    static var logoutConfirmMsg: String { return RTLocalizationSystem.rtLocalize("LogoutConfirm", comment: "")}
    static var loginFailedMsg: String { return RTLocalizationSystem.rtLocalize("LoginFailMessage", comment: "")}
    static var internetConnectionLost: String { return RTLocalizationSystem.rtLocalize("InternetConnectLost", comment: "")}
    static var dataNotFound: String { return RTLocalizationSystem.rtLocalize("DataNotFound", comment: "")}
    static var enterOTP: String { return RTLocalizationSystem.rtLocalize("EnterOTP", comment: "")}
    static var enterPhoneNumber: String { return RTLocalizationSystem.rtLocalize("EnterPhoneNumber", comment: "")}
    static var enterPassword: String { return RTLocalizationSystem.rtLocalize("EnterPassword", comment: "")}
    static var invalidPhoneNumber: String { return RTLocalizationSystem.rtLocalize("InvalidPhoneNumber", comment: "")}
    static var messageNotSupport: String { return RTLocalizationSystem.rtLocalize("DeviceCannotSendMsg", comment: "")}
    static var register: String { return RTLocalizationSystem.rtLocalize("Register", comment: "")}
    static var auto: String { return RTLocalizationSystem.rtLocalize("Auto", comment: "")}
    static var hiString: String { return RTLocalizationSystem.rtLocalize("myclip.hi", comment: "")}
    static var home: String { return RTLocalizationSystem.rtLocalize("myclip.Home", comment: "")}
    static var tVString: String { return RTLocalizationSystem.rtLocalize("myclip.TV", comment: "")}
    static var video: String { return RTLocalizationSystem.rtLocalize("myclip.Video", comment: "")}
    static var film: String { return RTLocalizationSystem.rtLocalize("myclip.Film", comment: "")}
    static var kids: String { return RTLocalizationSystem.rtLocalize("myclip.Kids", comment: "")}
    static var game: String { return RTLocalizationSystem.rtLocalize("myclip.Game", comment: "")}
    static var package: String { return RTLocalizationSystem.rtLocalize("myclip.Package", comment: "")}
    static var notification: String { return RTLocalizationSystem.rtLocalize("myclip.Notification", comment: "")}
    static var settings: String { return RTLocalizationSystem.rtLocalize("myclip.Settings", comment: "")}
    static var share: String { return RTLocalizationSystem.rtLocalize("myclip.Share", comment: "")}
    static var rateApp: String { return RTLocalizationSystem.rtLocalize("myclip.RateApp", comment: "")}
    static var viewAll: String { return RTLocalizationSystem.rtLocalize("myclip.ViewAll", comment: "")}
    static var tags: String { return RTLocalizationSystem.rtLocalize("myclip.Tags", comment: "")}
    static var actors: String { return RTLocalizationSystem.rtLocalize("myclip.Actors", comment: "")}
    static var country: String { return RTLocalizationSystem.rtLocalize("myclip.Country", comment: "")}
    static var tabProgramSchedule: String { return RTLocalizationSystem.rtLocalize("myclip.TabProgramSchedule", comment: "")}
    static var tabPart: String { return RTLocalizationSystem.rtLocalize("myclip.TabPart", comment: "")}
    static var tabRelate: String { return RTLocalizationSystem.rtLocalize("myclip.TabRelate", comment: "")}
    static var tabComment: String { return RTLocalizationSystem.rtLocalize("myclip.TabComment", comment: "")}
    static var today: String { return RTLocalizationSystem.rtLocalize("myclip.Today", comment: "")}
    static var expandAppendText: String { return RTLocalizationSystem.rtLocalize("myclip.ExpandAppendText", comment: "")}
    static var expandText: String { return RTLocalizationSystem.rtLocalize("myclip.ExpandText", comment: "")}
    static var reply: String { return RTLocalizationSystem.rtLocalize("myclip.Reply", comment: "")}
    static var quality: String { return RTLocalizationSystem.rtLocalize("myclip.quality.auto", comment: "")}
    static var searchPlaceHolder: String { return RTLocalizationSystem.rtLocalize("myclip.SearchPlaceHolder", comment: "")}
    static var searchNoResult: String { return RTLocalizationSystem.rtLocalize("myclip.SearchNoResult", comment: "")}
    static var chooseQuality: String { return RTLocalizationSystem.rtLocalize("myclip.ChooseQuality", comment: "")}
    static var chooseSpeed: String { return RTLocalizationSystem.rtLocalize("myclip.ChooseSpeed", comment: "")}
    static var part: String { return RTLocalizationSystem.rtLocalize("myclip.Part", comment: "")}
    static var account: String { return RTLocalizationSystem.rtLocalize("myclip.Account", comment: "")}
    static var feedback: String { return RTLocalizationSystem.rtLocalize("myclip.Feedback", comment: "")}
    static var appVersion: String { return RTLocalizationSystem.rtLocalize("myclip.AppVersion", comment: "")}
    static var aboutService: String { return RTLocalizationSystem.rtLocalize("myclip.AboutService", comment: "")}
    static var termOfUse: String { return RTLocalizationSystem.rtLocalize("myclip.TermOfUse", comment: "")}
    static var lougoutConfirm: String { return RTLocalizationSystem.rtLocalize("myclip.LougoutConfirm", comment: "")}
    static var report: String { return RTLocalizationSystem.rtLocalize("myclip.Report", comment: "")}
    static var choosePart: String { return RTLocalizationSystem.rtLocalize("myclip.ChoosePart", comment: "")}
    static var seeMoreComments: String { return RTLocalizationSystem.rtLocalize("myclip.SeeMoreComments", comment: "")}
    static var back: String { return RTLocalizationSystem.rtLocalize("myclip.Back", comment: "")}
    static var enterCaptcha: String { return RTLocalizationSystem.rtLocalize("myclip.EnterCaptcha", comment: "")}
    static var changePassword: String { return RTLocalizationSystem.rtLocalize("myclip.ChangePassword", comment: "")}
    static var enterOldPass: String { return RTLocalizationSystem.rtLocalize("myclip.EnterOldPass", comment: "")}
    static var enterNewPass: String { return RTLocalizationSystem.rtLocalize("myclip.EnterNewPass", comment: "")}
    static var enterConfirmNewPass: String { return RTLocalizationSystem.rtLocalize("myclip.EnterConfirmNewPass", comment: "")}
    static var oldPassEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.OldPassEmpty", comment: "")}
    static var newPassEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.NewPassEmpty", comment: "")}
    static var confirmPassEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmPassEmpty", comment: "")}
    static var passwordNotMatch: String { return RTLocalizationSystem.rtLocalize("myclip.PasswordNotMatch", comment: "")}
    static var shortPassword: String { return RTLocalizationSystem.rtLocalize("myclip.ShortPassword", comment: "")}
    static var differentOldPassword: String { return RTLocalizationSystem.rtLocalize("myclip.DifferentOldPass", comment: "")}
    static var changePasswordSuccess: String { return RTLocalizationSystem.rtLocalize("myclip.ChangePasswordSuccess", comment: "")}
    static var name: String { return RTLocalizationSystem.rtLocalize("myclip.Name", comment: "")}
    static var playlist: String { return RTLocalizationSystem.rtLocalize("myclip.Playlist", comment: "")}
    static var changePasswordFail: String { return RTLocalizationSystem.rtLocalize("myclip.ChangePasswordFail", comment: "")}
    static var enterNewPlaylistName: String { return RTLocalizationSystem.rtLocalize("myclip.EnterNewPlaylistName", comment: "")}
    static var updatePlaylist: String { return RTLocalizationSystem.rtLocalize("myclip.UpdatePlaylist", comment: "")}
    static var removePlaylist: String { return RTLocalizationSystem.rtLocalize("myclip.RemovePlaylist", comment: "")}
    static var luu: String { return RTLocalizationSystem.rtLocalize("luu", comment: "")}
    static var daang_ky: String { return RTLocalizationSystem.rtLocalize("daang_ky", comment: "")}
    static var huy_bo: String { return RTLocalizationSystem.rtLocalize("huy_bo", comment: "")}
    static var tai_khoan: String { return RTLocalizationSystem.rtLocalize("tai_khoan", comment: "")}
    static var chia_se: String { return RTLocalizationSystem.rtLocalize("chia_se", comment: "")}
    static var khong_co_du_lieu: String { return RTLocalizationSystem.rtLocalize("khong_co_du_lieu", comment: "")}
    static var enterPlaylistName: String { return RTLocalizationSystem.rtLocalize("myclip.EnterPlaylistName", comment: "")}
    static var updateSuccess: String { return RTLocalizationSystem.rtLocalize("myclip.UpdateSuccess", comment: "")}
    static var removeSuccess: String { return RTLocalizationSystem.rtLocalize("myclip.RemoveSuccess", comment: "")}
    static var addSuccess: String { return RTLocalizationSystem.rtLocalize("myclip.AddSuccess", comment: "")}
    static var removeFail: String { return RTLocalizationSystem.rtLocalize("myclip.RemoveFail", comment: "")}
    static var confirmRemovePlaylist: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmRemovePlaylist", comment: "")}
    static var contact: String { return RTLocalizationSystem.rtLocalize("myclip.Contact", comment: "")}
    static var introduce: String { return RTLocalizationSystem.rtLocalize("myclip.Introduce", comment: "")}
    static var confirm: String { return RTLocalizationSystem.rtLocalize("myclip.Confirm", comment: "")}
    static var cancelDo: String { return RTLocalizationSystem.rtLocalize("myclip.CancelDo", comment: "")}
    static var watchLater: String { return RTLocalizationSystem.rtLocalize("myclip.WatchLater", comment: "")}
    static var clearWatchHistory: String { return RTLocalizationSystem.rtLocalize("myclip.ClearWatchHistory", comment: "")}
    static var watchHistory: String { return RTLocalizationSystem.rtLocalize("myclip.WatchHistory", comment: "")}
    static var clearHistorySuccess: String { return RTLocalizationSystem.rtLocalize("myclip.ClearHistorySuccess", comment: "")}
    static var clearHistoryFail: String { return RTLocalizationSystem.rtLocalize("myclip.ClearHistoryFail", comment: "")}
    static var linkAccount: String { return RTLocalizationSystem.rtLocalize("myclip.LinkAccount", comment: "")}
    static var LINKACCOUNT: String { return RTLocalizationSystem.rtLocalize("myclip.LINKACCOUNT", comment: "")}
    static var phoneNumberEnter: String { return RTLocalizationSystem.rtLocalize("myclip.EnterPhoneNumber", comment: "")}
    static var enterOTPCode: String { return RTLocalizationSystem.rtLocalize("myclip.EnterOTPCode", comment: "")}
    static var getOTPCode: String { return RTLocalizationSystem.rtLocalize("myclip.GetOTPCode", comment: "")}
    static var otpSended: String { return RTLocalizationSystem.rtLocalize("myclip.OtpSended", comment: "")}
    static var otpNotSended: String { return RTLocalizationSystem.rtLocalize("myclip.OtpNotSended", comment: "")}
    static var linkAccountHint: String { return RTLocalizationSystem.rtLocalize("myclip.LinkAccountHint", comment: "")}
    static var linkAccountSuccess: String { return RTLocalizationSystem.rtLocalize("myclip.LinkAccountSuccess", comment: "")}
    static var linkAccountFail: String { return RTLocalizationSystem.rtLocalize("myclip.LinkAccountFail", comment: "")}
    static var logout: String { return RTLocalizationSystem.rtLocalize("myclip.Logout", comment: "")}
    static var login: String { return RTLocalizationSystem.rtLocalize("myclip.Login", comment: "")}
    static var getPassword: String { return RTLocalizationSystem.rtLocalize("myclip.GetPassword", comment: "")}
    static var phoneNumberEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.PhoneNumberEmpty", comment: "")}
    static var phoneNumberNotValid: String { return RTLocalizationSystem.rtLocalize("myclip.PhoneNumberNotValid", comment: "")}
    static var passwordEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.PasswordEmpty", comment: "")}
    static var sMSNotAvailabel: String { return RTLocalizationSystem.rtLocalize("myclip.SMSNotAvailabel", comment: "")}
    static var sendSMSFailed: String { return RTLocalizationSystem.rtLocalize("myclip.SendSMSFailed", comment: "")}
    static var registerPackage: String { return RTLocalizationSystem.rtLocalize("myclip.RegisterPackage", comment: "")}
    static var confirmPackageTitle: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmPackageTitle", comment: "" )}
    static var confirmPackage: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmPackage", comment: "" )}
    static var registerPackageMsg: String { return RTLocalizationSystem.rtLocalize("myclip.RegisterPackageMsg", comment: "" )}
    static var unregisterPackage: String { return RTLocalizationSystem.rtLocalize("myclip.UnregisterPackage", comment: "")}
    static var unregisterPackageConfirm: String { return RTLocalizationSystem.rtLocalize("myclip.UnregisterPackageConfirm", comment: "")}
    static var unregisterPackageMsg: String { return RTLocalizationSystem.rtLocalize("myclip.UnregisterPackageMsg", comment: "")}
    static var choosePackageRequireMsg: String { return RTLocalizationSystem.rtLocalize("myclip.ChoosePackageRequireMsg", comment: "")}
    static var cancelPackage: String {return RTLocalizationSystem.rtLocalize("myclip.Cancel", comment: "")}
    static var favorite: String { return RTLocalizationSystem.rtLocalize("myclip.favorite", comment: "")}
    static var continueWatch: String { return RTLocalizationSystem.rtLocalize("myclip.ContinueWatch", comment: "")}
    static var buyRetail: String { return RTLocalizationSystem.rtLocalize("myclip.BuyRetail", comment: "")}
    static var buyAllPart: String { return RTLocalizationSystem.rtLocalize("myclip.BuyAllPart", comment: "")}
    static var Register: String { return RTLocalizationSystem.rtLocalize("myclip.Register", comment: "")}
    static var Skip: String { return RTLocalizationSystem.rtLocalize("myclip.Skip", comment: "")}
    static var notLogIn: String { return RTLocalizationSystem.rtLocalize("myclip.NotLogIn", comment: "")}
    static var reLogin: String { return RTLocalizationSystem.rtLocalize("myclip.ReLogin", comment: "")}
    static var tokenInvalid: String { return RTLocalizationSystem.rtLocalize("myclip.TokenInvalid", comment: "")}
    static var require3G: String { return RTLocalizationSystem.rtLocalize("myclip.require3G", comment: "")}
    static var captchaEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.CaptchaEmpty", comment: "")}
    static var writeComment: String { return RTLocalizationSystem.rtLocalize("myclip.WriteComment", comment: "")}
    static var writeReply: String { return RTLocalizationSystem.rtLocalize("myclip.WriteReply", comment: "")}
    static var presenting: String { return RTLocalizationSystem.rtLocalize("myclip.Presenting", comment: "")}
    static var noData: String { return RTLocalizationSystem.rtLocalize("myclip.NoData", comment: "")}
    static var noDataVideoOffline: String { return RTLocalizationSystem.rtLocalize("myclip.NoDataVideoOffline", comment: "")}
    static var noScheduleData: String { return RTLocalizationSystem.rtLocalize("myclip.NoScheduleData", comment: "")}
    static var autoLogin3G: String { return RTLocalizationSystem.rtLocalize("myclip.AutoLogin3G", comment: "")}
    static var linkToShareNotAvailable: String { return RTLocalizationSystem.rtLocalize("myclip.LinkToShareNotAvailable", comment: "")}
    static var streamingURLError: String { return RTLocalizationSystem.rtLocalize("myclip.StreamingURLError", comment: "")}
    static var rewindTimeZero: String { return RTLocalizationSystem.rtLocalize("myclip.RewindTimeZero", comment: "")}
    static var contentRequireMsg: String { return RTLocalizationSystem.rtLocalize("myclip.ContentRequireMsg", comment: "")}
    static var noComment: String { return RTLocalizationSystem.rtLocalize("myclip.NoComment", comment: "")}
    static var liveCam: String { return RTLocalizationSystem.rtLocalize("myclip.LiveCam", comment: "")}
    static var liveCamTitleEmpty: String { return RTLocalizationSystem.rtLocalize("myclip.LiveCamTitleEmpty", comment: "")}
    static var liveCamClose: String { return RTLocalizationSystem.rtLocalize("myclip.LiveCamClose", comment: "")}
    static var liveCamStreamIsEnd: String { return RTLocalizationSystem.rtLocalize("myclip.LiveCamStreamIsEnd", comment: "")}
    static var welcome1Title: String { return RTLocalizationSystem.rtLocalize("myclip.welcome1Title", comment: "")}
    static var welcome2Title: String { return RTLocalizationSystem.rtLocalize("myclip.welcome2Title", comment: "")}
    static var welcome3Title: String { return RTLocalizationSystem.rtLocalize("myclip.welcome3Title", comment: "")}
    static var EditMyChannelTitle: String { return RTLocalizationSystem.rtLocalize("myclip.EditMyChannel", comment: "")}
    static var EmptyEditNameChannel: String { return RTLocalizationSystem.rtLocalize("myclip.EmptyEditNameChannel", comment: "")}
    static var EmptyEditDescriptionChannel: String { return RTLocalizationSystem.rtLocalize("myclip.EmptyEditDescriptionChannel", comment: "")}
    static var not_Internet: String { return RTLocalizationSystem.rtLocalize("Not_Internet", comment: "")}
    static var sYSTEM_BUSY: String { return RTLocalizationSystem.rtLocalize("SYSTEM_BUSY", comment: "")}
    static var topVideo: String { return RTLocalizationSystem.rtLocalize("TopVideo", comment: "")}
    static var friendVideo: String { return RTLocalizationSystem.rtLocalize("FriendVideo", comment: "")}
    static var newsVideo: String { return RTLocalizationSystem.rtLocalize("NewsVideo", comment: "")}
    static var topMusic: String { return RTLocalizationSystem.rtLocalize("TopMusic", comment: "")}
    static var friendMusic: String { return RTLocalizationSystem.rtLocalize("FriendMusic", comment: "")}
    static var newsMusic: String { return RTLocalizationSystem.rtLocalize("NewsMusic", comment: "")}
    static var homeFilm: String { return RTLocalizationSystem.rtLocalize("HomeFilm", comment: "")}
    static var filmNew: String { return RTLocalizationSystem.rtLocalize("FilmNew", comment: "")}
    static var top: String { return RTLocalizationSystem.rtLocalize("Top", comment: "")}
    static var follow: String { return RTLocalizationSystem.rtLocalize("Follow", comment: "")}
    static var unFollow: String { return RTLocalizationSystem.rtLocalize("UnFollow", comment: "")}
    static var fREE_DATA: String { return RTLocalizationSystem.rtLocalize("FREE_DATA", comment: "")}
    static var confirmClearHistory: String { return RTLocalizationSystem.rtLocalize("myclip.ComfirmClearHistory", comment: "")}
    static var confirmClearAllHistorySearch: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmClearSearchAllHistory", comment: "")}
    static var confirmClearHistorySearch: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmClearSearchHistory", comment: "")}
    static var confirmClearDownload: String { return RTLocalizationSystem.rtLocalize("myclip.ConfirmClearDownload", comment: "")}
    static var onToggleSettingsNoti: String { return RTLocalizationSystem.rtLocalize("myclip.onToggleSettingsNoti", comment: "")}
    static var offToggleSettingsNoti: String { return RTLocalizationSystem.rtLocalize("myclip.offToggleSettingsNoti", comment: "")}
    static var noSpeechSearchVoice: String { return RTLocalizationSystem.rtLocalize("myclip.noSpeechSearchVoice", comment: "")}
    static var startSpeech: String { return RTLocalizationSystem.rtLocalize("myclip.startSpeech", comment: "")}
    static var registerSubTitle: String { return RTLocalizationSystem.rtLocalize("RegisterSubTitle", comment: "")}
    static var unregisterSubTitle: String { return RTLocalizationSystem.rtLocalize("UnregisterSubTitle", comment: "")}
    static var registerSubSuccess: String { return RTLocalizationSystem.rtLocalize("RegisterSubSuccess", comment: "")}
    static var registerSubNotSuccess: String { return RTLocalizationSystem.rtLocalize("RegisterSubNotSuccess", comment: "")}
    static var unregisterSubSuccess: String { return RTLocalizationSystem.rtLocalize("UnregisterSubSuccess", comment: "")}
    static var unregisterSubNotSuccess: String { return RTLocalizationSystem.rtLocalize("UnregisterSubNotSuccess", comment: "")}
    static var saveConfirm: String { return RTLocalizationSystem.rtLocalize("SaveConfirm", comment: "")}
    static var callConfirm: String { return RTLocalizationSystem.rtLocalize("Call198Confirm", comment: "")}
    static var requestAccessConfirm: String { return RTLocalizationSystem.rtLocalize("SettingConfirm", comment: "")}
    static var notificationConfirm: String { return RTLocalizationSystem.rtLocalize("NotificationConfirm", comment: "")}
    static var UnFollowChannelTitle: String { return RTLocalizationSystem.rtLocalize("UnFollowChannelTitle", comment: "")}
    static var UnFollowChannelDesc: String { return RTLocalizationSystem.rtLocalize("UnFollowChannelDesc", comment: "")}
    static var EnterName: String { return RTLocalizationSystem.rtLocalize("EnterName", comment: "")}
    static var EnterEmail: String { return RTLocalizationSystem.rtLocalize("EnterEmail", comment: "")}
    static var EnterIDNo: String { return RTLocalizationSystem.rtLocalize("EnterIDNo", comment: "")}
    static var EnterIDAddress: String { return RTLocalizationSystem.rtLocalize("EnterIDAddress", comment: "")}
    static var EnterIDDate: String { return RTLocalizationSystem.rtLocalize("EnterIDDate", comment: "")}
    static var EnterIDFrontImage: String { return RTLocalizationSystem.rtLocalize("EnterIDFrontImage", comment: "")}
    static var EnterIDBackImage: String { return RTLocalizationSystem.rtLocalize("EnterIDBackImage", comment: "")}
    static var EnterPhoneOTP: String { return RTLocalizationSystem.rtLocalize("EnterPhoneOTP", comment: "")}
    static var EnterAcceptTerm: String { return RTLocalizationSystem.rtLocalize("EnterAcceptTerm", comment: "")}
    static var RemoveRelatedChannel: String { return RTLocalizationSystem.rtLocalize("RemoveRelatedChannel", comment: "")}
    static var EnterAccountNo: String { return RTLocalizationSystem.rtLocalize("EnterAccountNo", comment: "")}
    static var EnterBankInfor: String { return RTLocalizationSystem.rtLocalize("EnterBankInfor", comment: "")}
    static var EnterBankBranche: String { return RTLocalizationSystem.rtLocalize("EnterBankBranche", comment: "")}
    static var EnterMST: String { return RTLocalizationSystem.rtLocalize("EnterMST", comment: "")}
    static var EnterBankAddress: String { return RTLocalizationSystem.rtLocalize("EnterBankAddress", comment: "")}
    static var EnterVTPPhone: String { return RTLocalizationSystem.rtLocalize("EnterVTPPhone", comment: "")}
    static var ban_co_dong_y_xoa_kenh_lien_quan_nay_khong: String { return RTLocalizationSystem.rtLocalize("ban_co_dong_y_xoa_kenh_lien_quan_nay_khong", comment: "")}
    static var cong_khai: String { return RTLocalizationSystem.rtLocalize("cong_khai", comment: "")}
    static var khong_cong_khai: String { return RTLocalizationSystem.rtLocalize("khong_cong_khai", comment: "")}
    static var chuan: String { return RTLocalizationSystem.rtLocalize("chuan", comment: "")}
    static var da_phe_duyet: String { return RTLocalizationSystem.rtLocalize("da_phe_duyet", comment: "")}
    static var tu_choi_duyet: String { return RTLocalizationSystem.rtLocalize("tu_choi_duyet", comment: "")}
    static var cho_phe_duyet_chua_xem_duoc: String { return RTLocalizationSystem.rtLocalize("cho_phe_duyet_chua_xem_duoc", comment: "")}
    static var tai_len: String { return RTLocalizationSystem.rtLocalize("tai_len", comment: "")}
    static var Next: String { return RTLocalizationSystem.rtLocalize("Next", comment: "")}
    static var ngay: String { return RTLocalizationSystem.rtLocalize("ngay", comment: "")}
    static var thang: String { return RTLocalizationSystem.rtLocalize("thang", comment: "")}
    static var giay: String { return RTLocalizationSystem.rtLocalize("giay", comment: "")}
    static var phut: String { return RTLocalizationSystem.rtLocalize("phut", comment: "")}
    static var gio: String { return RTLocalizationSystem.rtLocalize("gio", comment: "")}
    static var nam: String { return RTLocalizationSystem.rtLocalize("nam", comment: "")}
    static var tuan: String { return RTLocalizationSystem.rtLocalize("tuan", comment: "")}
    static var truoc: String { return RTLocalizationSystem.rtLocalize("truoc", comment: "")}
    static var da_xoa_video_tai_xuong: String { return RTLocalizationSystem.rtLocalize("da_xoa_video_tai_xuong", comment: "")}
    static var xem_video_tai_xuong_trong_trang_ca_nhan: String { return RTLocalizationSystem.rtLocalize("xem_video_tai_xuong_trong_trang_ca_nhan", comment: "")}
    static var tai_xuong: String { return RTLocalizationSystem.rtLocalize("tai_xuong", comment: "")}
    static var giai_thuong_thang: String { return RTLocalizationSystem.rtLocalize("giai_thuong_thang", comment: "")}
    static var giai_thuong_tuan: String { return RTLocalizationSystem.rtLocalize("giai_thuong_tuan", comment: "")}
    static var tai_xuong_loi: String { return RTLocalizationSystem.rtLocalize("tai_xuong_loi", comment: "")}
    static var nguoi_dang_ky: String { return RTLocalizationSystem.rtLocalize("nguoi_dang_ky", comment: "")}
    static var dang_tai_xuong: String { return RTLocalizationSystem.rtLocalize("dang_tai_xuong", comment: "")}
    static var thong_tin_thanh_toan: String { return RTLocalizationSystem.rtLocalize("thong_tin_thanh_toan", comment: "")}
    static var dang_ky_thong_tin_thanh_toan_khong_hop_le: String { return RTLocalizationSystem.rtLocalize("dang_ky_thong_tin_thanh_toan_khong_hop_le", comment: "")}
    static var PaymentMethod: String { return RTLocalizationSystem.rtLocalize("PaymentMethod", comment: "")}
    static var link_register_viettel_pay: String { return RTLocalizationSystem.rtLocalize("link_register_viettel_pay", comment: "")}
    static var cap_nhat_thanh_cong: String { return RTLocalizationSystem.rtLocalize("cap_nhat_thanh_cong", comment: "")}
    static var xac_nhan_thong_tin_ca_nhan: String { return RTLocalizationSystem.rtLocalize("xac_nhan_thong_tin_ca_nhan", comment: "")}
    static var chon_ngay: String { return RTLocalizationSystem.rtLocalize("chon_ngay", comment: "")}
    static var chup_anh: String { return RTLocalizationSystem.rtLocalize("chup_anh", comment: "")}
    static var chon_tu_thu_vien: String { return RTLocalizationSystem.rtLocalize("chon_tu_thu_vien", comment: "")}
    static var chon_anh_mat_truoc: String { return RTLocalizationSystem.rtLocalize("chon_anh_mat_truoc", comment: "")}
    static var chon_anh_mat_sau: String { return RTLocalizationSystem.rtLocalize("chon_anh_mat_sau", comment: "")}
    static var thanh_cong: String { return RTLocalizationSystem.rtLocalize("thanh_cong", comment: "")}
    static var thiet_bi_cua_ban_khong_the_chup_anh: String { return RTLocalizationSystem.rtLocalize("thiet_bi_cua_ban_khong_the_chup_anh", comment: "")}
    static var khong_the_tai_anh: String { return RTLocalizationSystem.rtLocalize("khong_the_tai_anh", comment: "")}
    static var thu_nhap: String { return RTLocalizationSystem.rtLocalize("thu_nhap", comment: "")}
    static var tu: String { return RTLocalizationSystem.rtLocalize("tu", comment: "")}
    static var den: String { return RTLocalizationSystem.rtLocalize("den", comment: "")}
    static var su_kien: String { return RTLocalizationSystem.rtLocalize("su_kien", comment: "")}
    static var diem_cua_toi: String { return RTLocalizationSystem.rtLocalize("diem_cua_toi", comment: "")}
    static var the_le: String { return RTLocalizationSystem.rtLocalize("the_le", comment: "")}
    static var giai_thuong: String { return RTLocalizationSystem.rtLocalize("giai_thuong", comment: "")}
    static var video_tai_xuong: String { return RTLocalizationSystem.rtLocalize("video_tai_xuong", comment: "")}
    static var xoa_tai_xuong: String { return RTLocalizationSystem.rtLocalize("xoa_tai_xuong", comment: "")}
    static var thiet_bi_khong_ho_tro_nhan_tin: String { return RTLocalizationSystem.rtLocalize("thiet_bi_khong_ho_tro_nhan_tin", comment: "")}
    static var xin_chao: String { return RTLocalizationSystem.rtLocalize("xin_chao", comment: "")}
    static var dang_tai_len: String { return RTLocalizationSystem.rtLocalize("dang_tai_len", comment: "")}
    static var xoa_xem_gan_day: String { return RTLocalizationSystem.rtLocalize("xoa_xem_gan_day", comment: "")}
    static var them_vao_danh_sach_phat: String { return RTLocalizationSystem.rtLocalize("them_vao_danh_sach_phat", comment: "")}
    static var xoa_khoi_danh_sach: String { return RTLocalizationSystem.rtLocalize("xoa_khoi_danh_sach", comment: "")}
    static var xoa_noi_dung_khoi_thu_muc_tai_xuong: String { return RTLocalizationSystem.rtLocalize("xoa_noi_dung_khoi_thu_muc_tai_xuong", comment: "")}
    static var dang_cho: String { return RTLocalizationSystem.rtLocalize("dang_cho", comment: "")}
    static var dang_xu_ly: String { return RTLocalizationSystem.rtLocalize("dang_xu_ly", comment: "")}
    static var tai_len_loi: String { return RTLocalizationSystem.rtLocalize("tai_len_loi", comment: "")}
    static var video_cua_toi: String { return RTLocalizationSystem.rtLocalize("video_cua_toi", comment: "")}
    static var xoa_tai_len: String { return RTLocalizationSystem.rtLocalize("xoa_tai_len", comment: "")}
    static var them_vao_xem_sau: String { return RTLocalizationSystem.rtLocalize("them_vao_xem_sau", comment: "")}
    static var them_vao: String { return RTLocalizationSystem.rtLocalize("them_vao", comment: "")}
    static var xoa_video: String { return RTLocalizationSystem.rtLocalize("xoa_video", comment: "")}
    static var chon_anh: String { return RTLocalizationSystem.rtLocalize("chon_anh", comment: "")}
    static var nhap_noi_dung_phan_hoi: String { return RTLocalizationSystem.rtLocalize("nhap_noi_dung_phan_hoi", comment: "")}
    static var gui_phan_hoi_thanh_cong: String { return RTLocalizationSystem.rtLocalize("gui_phan_hoi_thanh_cong", comment: "")}
    static var da_gui_y_kien: String { return RTLocalizationSystem.rtLocalize("da_gui_y_kien", comment: "")}
    static var gui_y_kien: String { return RTLocalizationSystem.rtLocalize("gui_y_kien", comment: "")}
    static var dong: String { return RTLocalizationSystem.rtLocalize("dong", comment: "")}
    static var phan_hoi_dang_duoc_quan_tri_vien_xem_xet: String { return RTLocalizationSystem.rtLocalize("phan_hoi_dang_duoc_quan_tri_vien_xem_xet", comment: "")}
    static var noi_dung_khong_duoc_chap_nhan_voi_ly_do: String { return RTLocalizationSystem.rtLocalize("noi_dung_khong_duoc_chap_nhan_voi_ly_do", comment: "")}
    static var xem_sau: String { return RTLocalizationSystem.rtLocalize("xem_sau", comment: "")}
    static var tao_danh_sach_phat_moi: String { return RTLocalizationSystem.rtLocalize("tao_danh_sach_phat_moi", comment: "")}
    static var ten_danh_sach_phat: String { return RTLocalizationSystem.rtLocalize("ten_danh_sach_phat", comment: "")}
    static var chinh_sua: String { return RTLocalizationSystem.rtLocalize("chinh_sua", comment: "")}
    static var theo_doi: String { return RTLocalizationSystem.rtLocalize("theo_doi", comment: "")}
    static var theo_doi_btn: String { return RTLocalizationSystem.rtLocalize("theo_doi_btn", comment: "")}
    
    static var sap_xep_theo: String { return RTLocalizationSystem.rtLocalize("sap_xep_theo", comment: "")}
    static var cai_dat_chat_luong_video: String { return RTLocalizationSystem.rtLocalize("cai_dat_chat_luong_video", comment: "")}
    static var phien_ban_ung_dung: String { return RTLocalizationSystem.rtLocalize("phien_ban_ung_dung", comment: "")}
    static var danh_gia_ung_dung: String { return RTLocalizationSystem.rtLocalize("danh_gia_ung_dung", comment: "")}
    static var cai_dat_thong_bao: String { return RTLocalizationSystem.rtLocalize("cai_dat_thong_bao", comment: "")}
    static var chi_phat_hd_tren_wifi: String { return RTLocalizationSystem.rtLocalize("chi_phat_hd_tren_wifi", comment: "")}
    static var hinh_dai_dien: String { return RTLocalizationSystem.rtLocalize("hinh_dai_dien", comment: "")}
    static var che_do: String { return RTLocalizationSystem.rtLocalize("che_do", comment: "")}
    static var bo_qua: String { return RTLocalizationSystem.rtLocalize("bo_qua", comment: "")}
    static var dung_thu_1_thang_mien_phi: String { return RTLocalizationSystem.rtLocalize("dung_thu_1_thang_mien_phi", comment: "")}
    static var xac_nhan: String { return RTLocalizationSystem.rtLocalize("xac_nhan", comment: "")}
    static var lay_ma_otp: String { return RTLocalizationSystem.rtLocalize("lay_ma_otp", comment: "")}
    static var bat_buoc_nhap: String { return RTLocalizationSystem.rtLocalize("bat_buoc_nhap", comment: "")}
    static var thong_tin_ca_nhan: String { return RTLocalizationSystem.rtLocalize("thong_tin_ca_nhan", comment: "")}
    static var anh_mat_truoc: String { return RTLocalizationSystem.rtLocalize("anh_mat_truoc", comment: "")}
    static var anh_mat_sau: String { return RTLocalizationSystem.rtLocalize("anh_mat_sau", comment: "")}
    static var tuong_tac_cua_ban: String { return RTLocalizationSystem.rtLocalize("tuong_tac_cua_ban", comment: "")}
    static var xem_video: String { return RTLocalizationSystem.rtLocalize("xem_video", comment: "")}
    static var chia_se_video: String { return RTLocalizationSystem.rtLocalize("chia_se_video", comment: "")}
    static var thich_video: String { return RTLocalizationSystem.rtLocalize("thich_video", comment: "")}
    static var theo_doi_kenh: String { return RTLocalizationSystem.rtLocalize("theo_doi_kenh", comment: "")}
    static var dang_ky_kenh: String { return RTLocalizationSystem.rtLocalize("dang_ky_kenh", comment: "")}
    static var khong_thich_video: String { return RTLocalizationSystem.rtLocalize("khong_thich_video", comment: "")}
    static var tong_diem: String { return RTLocalizationSystem.rtLocalize("tong_diem", comment: "")}
    static var thu_nhap_hang_thang: String { return RTLocalizationSystem.rtLocalize("thu_nhap_hang_thang", comment: "")}
    static var thoi_gian: String { return RTLocalizationSystem.rtLocalize("thoi_gian", comment: "")}
    static var trang_thai: String { return RTLocalizationSystem.rtLocalize("trang_thai", comment: "")}
    static var tham_gia_ngay: String { return RTLocalizationSystem.rtLocalize("tham_gia_ngay", comment: "")}
    static var chon_thang: String { return RTLocalizationSystem.rtLocalize("chon_thang", comment: "")}
    static var tat_ca_tra_loi: String { return RTLocalizationSystem.rtLocalize("tat_ca_tra_loi", comment: "")}
    static var co_the_ban_thich: String { return RTLocalizationSystem.rtLocalize("co_the_ban_thich", comment: "")}
    static var them_cau_tra_loi: String { return RTLocalizationSystem.rtLocalize("them_cau_tra_loi", comment: "")}
    static var dang_nhap: String { return RTLocalizationSystem.rtLocalize("chuyen_den_video_cua_toi", comment: "")}
    static var signin_now_to_upload: String { return RTLocalizationSystem.rtLocalize("chuyen_den_video_cua_toi", comment: "")}
    static var chuyen_den_video_cua_toi: String { return RTLocalizationSystem.rtLocalize("chuyen_den_video_cua_toi", comment: "")}
    static var daang_tai_thanh_cong: String { return RTLocalizationSystem.rtLocalize("daang_tai_thanh_cong", comment: "")}
    static var quay_video: String { return RTLocalizationSystem.rtLocalize("quay_video", comment: "")}
    static var toi_thieu_6_ky_tu: String { return RTLocalizationSystem.rtLocalize("toi_thieu_6_ky_tu", comment: "")}
    static var da_dang_ky: String { return RTLocalizationSystem.rtLocalize("da_dang_ky", comment: "")}
    static var toi_da_doc_va_dong_y: String { return RTLocalizationSystem.rtLocalize("toi_da_doc_va_dong_y", comment: "")}
    static var tra_cuu_mst: String { return RTLocalizationSystem.rtLocalize("tra_cuu_mst", comment: "")}
    static var hinh_thuc_nhan_tien: String { return RTLocalizationSystem.rtLocalize("hinh_thuc_nhan_tien", comment: "")}
    static var nhap_lai_thong_tin: String { return RTLocalizationSystem.rtLocalize("nhap_lai_thong_tin", comment: "")}
    static var tai_khoan_da_duoc_duyet: String { return RTLocalizationSystem.rtLocalize("tai_khoan_da_duoc_duyet", comment: "")}
    static var ban_co_the_dang_tai_video: String { return RTLocalizationSystem.rtLocalize("ban_co_the_dang_tai_video", comment: "")}
    static var file: String { return RTLocalizationSystem.rtLocalize("file", comment: "")}
    static var chuyen_den_video_tai_xuong: String { return RTLocalizationSystem.rtLocalize("chuyen_den_video_tai_xuong", comment: "")}
    static var ban_dang_ngoai_tuyen: String { return RTLocalizationSystem.rtLocalize("ban_dang_ngoai_tuyen", comment: "")}
    static var tai_lai: String { return RTLocalizationSystem.rtLocalize("tai_lai", comment: "")}
    static var so_thue_bao: String { return RTLocalizationSystem.rtLocalize("so_thue_bao", comment: "")}
    static var xem_them: String { return RTLocalizationSystem.rtLocalize("xem_them", comment: "")}
    static var nhap_ma_xac_nhan: String { return RTLocalizationSystem.rtLocalize("nhap_ma_xac_nhan", comment: "")}
    static var nhap_so_dien_thoai: String { return RTLocalizationSystem.rtLocalize("nhap_so_dien_thoai", comment: "")}
    static var nhap_mat_khau: String { return RTLocalizationSystem.rtLocalize("nhap_mat_khau", comment: "")}
    static var dang_ky_tai_khoan: String { return RTLocalizationSystem.rtLocalize("dang_ky_tai_khoan", comment: "")}
    static var lay_mat_khau: String { return RTLocalizationSystem.rtLocalize("lay_mat_khau", comment: "")}
    static var binh_luan: String { return RTLocalizationSystem.rtLocalize("binh_luan", comment: "")}
    static var viet_binh_luan: String { return RTLocalizationSystem.rtLocalize("viet_binh_luan", comment: "")}
    static var danh_sach_theo_doi: String { return RTLocalizationSystem.rtLocalize("danh_sach_theo_doi", comment: "")}
    static var chinh_sua_video: String { return RTLocalizationSystem.rtLocalize("chinh_sua_video", comment: "")}
    static var tiep_tuc: String { return RTLocalizationSystem.rtLocalize("tiep_tuc", comment: "")}
    static var loai_bo_nhung_thay_doi: String { return RTLocalizationSystem.rtLocalize("loai_bo_nhung_thay_doi", comment: "")}
    static var noi_dung_ban_da_chon: String { return RTLocalizationSystem.rtLocalize("noi_dung_ban_da_chon", comment: "")}
    static var noi_dung_de_xuat: String { return RTLocalizationSystem.rtLocalize("noi_dung_de_xuat", comment: "")}
    static var chon_noi_dung: String { return RTLocalizationSystem.rtLocalize("chon_noi_dung", comment: "")}
    static var keo_tha_de_sap_xep_vi_tri_hien_thi_noi_dung: String { return RTLocalizationSystem.rtLocalize("keo_tha_de_sap_xep_vi_tri_hien_thi_noi_dung", comment: "")}
    static var chon_noi_dung_yeu_thich_ben_duoi: String { return RTLocalizationSystem.rtLocalize("chon_noi_dung_yeu_thich_ben_duoi", comment: "")}
    static var mat_khau_cu: String { return RTLocalizationSystem.rtLocalize("mat_khau_cu", comment: "")}
    static var mat_khau_moi: String { return RTLocalizationSystem.rtLocalize("mat_khau_moi", comment: "")}
    static var xac_nhan_mat_khau_moi: String { return RTLocalizationSystem.rtLocalize("xac_nhan_mat_khau_moi", comment: "")}
    static var ma_captcha: String { return RTLocalizationSystem.rtLocalize("ma_captcha", comment: "")}
    static var yeu_cau_nang_cap_phien_ban_moi: String { return RTLocalizationSystem.rtLocalize("yeu_cau_nang_cap_phien_ban_moi", comment: "")}
    static var nang_cap: String { return RTLocalizationSystem.rtLocalize("nang_cap", comment: "")}
    static var thoat: String { return RTLocalizationSystem.rtLocalize("thoat", comment: "")}
    static var co_phien_ban_moi: String { return RTLocalizationSystem.rtLocalize("co_phien_ban_moi", comment: "")}
    static var dung_hoi_lai: String { return RTLocalizationSystem.rtLocalize("dung_hoi_lai", comment: "")}
    static var de_xuat: String { return RTLocalizationSystem.rtLocalize("de_xuat", comment: "")}
    static var thinh_hanh: String { return RTLocalizationSystem.rtLocalize("thinh_hanh", comment: "")}
    static var ca_nhan: String { return RTLocalizationSystem.rtLocalize("ca_nhan", comment: "")}
    static var trang_chu: String { return RTLocalizationSystem.rtLocalize("trang_chu", comment: "")}
    static var den_tai_xuong: String { return RTLocalizationSystem.rtLocalize("den_tai_xuong", comment: "")}
    static var khong_co_ket_noi: String { return RTLocalizationSystem.rtLocalize("khong_co_ket_noi", comment: "")}
    static var da_thiet_lap_ket_noi: String { return RTLocalizationSystem.rtLocalize("da_thiet_lap_ket_noi", comment: "")}
    static var thong_bao: String { return RTLocalizationSystem.rtLocalize("thong_bao", comment: "")}
    static var bo_nho_khong_du_tai_video: String { return RTLocalizationSystem.rtLocalize("bo_nho_khong_du_tai_video", comment: "")}
    static var xem: String { return RTLocalizationSystem.rtLocalize("xem", comment: "")}
    static var tai_xuong_thanh_cong: String { return RTLocalizationSystem.rtLocalize("tai_xuong_thanh_cong", comment: "")}
    static var tai_len_thanh_cong: String { return RTLocalizationSystem.rtLocalize("tai_len_thanh_cong", comment: "")}
    static var daang_tai: String { return RTLocalizationSystem.rtLocalize("daang_tai", comment: "")}
    static var tat_thong_bao_kenh_nay: String { return RTLocalizationSystem.rtLocalize("tat_thong_bao_kenh_nay", comment: "")}
    static var tat_thong_bao: String { return RTLocalizationSystem.rtLocalize("tat_thong_bao", comment: "")}
    static var ban_co_muon_tat_thong_bao_kenh_nay_khong: String { return RTLocalizationSystem.rtLocalize("ban_co_muon_tat_thong_bao_kenh_nay_khong", comment: "")}
    static var thiet_bi_cua_ban_khong_ho_tro_camera: String { return RTLocalizationSystem.rtLocalize("thiet_bi_cua_ban_khong_ho_tro_camera", comment: "")}
    static var khong_co_video_trong_bo_nho_dien_thoai: String { return RTLocalizationSystem.rtLocalize("khong_co_video_trong_bo_nho_dien_thoai", comment: "")}
    static var daang_tai_video: String { return RTLocalizationSystem.rtLocalize("daang_tai_video", comment: "")}
    static var mo_ta: String { return RTLocalizationSystem.rtLocalize("mo_ta", comment: "")}
    static var bat_dau_chuong_trinh: String { return RTLocalizationSystem.rtLocalize("bat_dau_chuong_trinh", comment: "")}
    static var mo_cai_dat: String { return RTLocalizationSystem.rtLocalize("mo_cai_dat", comment: "")}
    static var huy: String { return RTLocalizationSystem.rtLocalize("huy", comment: "")}
    static var chon_hinh_dai_dien: String { return RTLocalizationSystem.rtLocalize("chon_hinh_dai_dien", comment: "")}
    static var chua_chon_video: String { return RTLocalizationSystem.rtLocalize("chua_chon_video", comment: "")}
    static var tieu_de: String { return RTLocalizationSystem.rtLocalize("tieu_de", comment: "")}
    static var tieu_de_khong_duoc_de_trong: String { return RTLocalizationSystem.rtLocalize("tieu_de_khong_duoc_de_trong", comment: "")}
    static var anh_dai_dien_khong_duoc_de_trong: String { return RTLocalizationSystem.rtLocalize("anh_dai_dien_khong_duoc_de_trong", comment: "")}
    static var dung_luong_khong_duoc_vuot_qua_1gb: String { return RTLocalizationSystem.rtLocalize("dung_luong_khong_duoc_vuot_qua_1gb", comment: "")}
    static var chinh_sua_ten: String { return RTLocalizationSystem.rtLocalize("chinh_sua_ten", comment: "")}
    static var ten_day_du: String { return RTLocalizationSystem.rtLocalize("ten_day_du", comment: "")}
    static var chinh_sua_mo_ta: String { return RTLocalizationSystem.rtLocalize("chinh_sua_mo_ta", comment: "")}
    static var cai_dat_kenh: String { return RTLocalizationSystem.rtLocalize("cai_dat_kenh", comment: "")}
    static var dang_cho_duyet: String { return RTLocalizationSystem.rtLocalize("dang_cho_duyet", comment: "")}
    static var da_duyet: String { return RTLocalizationSystem.rtLocalize("da_duyet", comment: "")}
    static var tu_choi: String { return RTLocalizationSystem.rtLocalize("tu_choi", comment: "")}
    static var ly_do: String { return RTLocalizationSystem.rtLocalize("ly_do", comment: "")}
    static var chon_hinh_nen_dai_dien: String { return RTLocalizationSystem.rtLocalize("chon_hinh_nen_dai_dien", comment: "")}
    static var xoa_lich_su_tim_kiem: String { return RTLocalizationSystem.rtLocalize("xoa_lich_su_tim_kiem", comment: "")}
    static var dong_y: String { return RTLocalizationSystem.rtLocalize("dong_y", comment: "")}
    static var xoa_lich_su_xem: String { return RTLocalizationSystem.rtLocalize("xoa_lich_su_xem", comment: "")}
    static var cai_dat: String { return RTLocalizationSystem.rtLocalize("cai_dat", comment: "")}
    static var dang_ky_nhan_tien: String { return RTLocalizationSystem.rtLocalize("dang_ky_nhan_tien", comment: "")}
    static var payment_infomation: String { return RTLocalizationSystem.rtLocalize("payment_infomation", comment: "")}
    static var goi_cuoc: String { return RTLocalizationSystem.rtLocalize("goi_cuoc", comment: "")}
    static var xem_gan_day: String { return RTLocalizationSystem.rtLocalize("xem_gan_day", comment: "")}
    static var danh_sach_phat: String { return RTLocalizationSystem.rtLocalize("danh_sach_phat", comment: "")}
    static var gioi_thieu: String { return RTLocalizationSystem.rtLocalize("gioi_thieu", comment: "")}
    static var dieu_khoan_va_chinh_sach_bao_mat: String { return RTLocalizationSystem.rtLocalize("dieu_khoan_va_chinh_sach_bao_mat", comment: "")}
    static var lien_he: String { return RTLocalizationSystem.rtLocalize("lien_he", comment: "")}
    static var doi_mat_khau: String { return RTLocalizationSystem.rtLocalize("doi_mat_khau", comment: "")}
    static var dang_xuat: String { return RTLocalizationSystem.rtLocalize("dang_xuat", comment: "")}
    static var goi: String { return RTLocalizationSystem.rtLocalize("goi", comment: "")}
    static var vui_long_nhap_noi_dung_tim_kiem: String { return RTLocalizationSystem.rtLocalize("vui_long_nhap_noi_dung_tim_kiem", comment: "")}
    static var ban_co_xoa_binh_luan_nay_khong: String { return RTLocalizationSystem.rtLocalize("ban_co_xoa_binh_luan_nay_khong", comment: "")}
    static var video_dang_tai_xuong: String { return RTLocalizationSystem.rtLocalize("video_dang_tai_xuong", comment: "")}
    static var xoa_khoi_danh_sach_video_tai_xuong: String { return RTLocalizationSystem.rtLocalize("xoa_khoi_danh_sach_video_tai_xuong", comment: "")}
    static var video_nay_se_khong_co_san_de_xem_ngoai_tuyen: String { return RTLocalizationSystem.rtLocalize("video_nay_se_khong_co_san_de_xem_ngoai_tuyen", comment: "")}
    static var xoa: String { return RTLocalizationSystem.rtLocalize("xoa", comment: "")}
    static var cau_tra_loi: String { return RTLocalizationSystem.rtLocalize("cau_tra_loi", comment: "")}
    static var dang_vao: String { return RTLocalizationSystem.rtLocalize("dang_vao", comment: "")}
    static var luot_xem: String { return RTLocalizationSystem.rtLocalize("luot_xem", comment: "")}
    static var them_kenh: String { return RTLocalizationSystem.rtLocalize("them_kenh", comment: "")}
    static var xem_tat_ca: String { return RTLocalizationSystem.rtLocalize("xem_tat_ca", comment: "")}
    static var videos: String { return RTLocalizationSystem.rtLocalize("Videos", comment: "")}
    static var luot_theo_doi: String { return RTLocalizationSystem.rtLocalize("luot_theo_doi", comment: "")}
    static var xem_nhieu_nhat: String { return RTLocalizationSystem.rtLocalize("xem_nhieu_nhat", comment: "")}
    static var moi_nhat: String { return RTLocalizationSystem.rtLocalize("moi_nhat", comment: "")}
    static var cu_nhat: String { return RTLocalizationSystem.rtLocalize("cu_nhat", comment: "")}
    static var kenh: String { return RTLocalizationSystem.rtLocalize("kenh", comment: "")}
    static var xem_tiep: String { return RTLocalizationSystem.rtLocalize("xem_tiep", comment: "")}
    static var tu_dong_phat: String { return RTLocalizationSystem.rtLocalize("tu_dong_phat", comment: "")}
    static var thiet_bi_khong_the_thuc_hien_cuoc_goi: String { return RTLocalizationSystem.rtLocalize("thiet_bi_khong_the_thuc_hien_cuoc_goi", comment: "")}
    static var chat_luong: String { return RTLocalizationSystem.rtLocalize("chat_luong", comment: "")}
    static var bao_cao: String { return RTLocalizationSystem.rtLocalize("bao_cao", comment: "")}
    static var toc_do: String { return RTLocalizationSystem.rtLocalize("toc_do", comment: "")}
    static var tiep_theo: String { return RTLocalizationSystem.rtLocalize("tiep_theo", comment: "")}
    static var chuong_trinh_se_bat_dau_sau: String { return RTLocalizationSystem.rtLocalize("chuong_trinh_se_bat_dau_sau", comment: "")}
    static var dang_phat_tren: String { return RTLocalizationSystem.rtLocalize("dang_phat_tren", comment: "")}
    static var thay_doi_ngon_ngu: String { return RTLocalizationSystem.rtLocalize("thay_doi_ngon_ngu", comment: "")}
    static var tieng_viet: String { return RTLocalizationSystem.rtLocalize("tieng_viet", comment: "")}
    static var tieng_mov: String { return RTLocalizationSystem.rtLocalize("tieng_mov", comment: "")}
    static var tieng_anh: String { return RTLocalizationSystem.rtLocalize("tieng_anh", comment: "")}
    static var bat_dau: String { return RTLocalizationSystem.rtLocalize("bat_dau", comment: "")}
    static var yeu_cau_restart_app: String { return RTLocalizationSystem.rtLocalize("yeu_cau_restart_app", comment: "")}
    static var su_dung_thong_tin_co_san: String { return RTLocalizationSystem.rtLocalize("su_dung_thong_tin_co_san", comment: "")}
    static var ho_va_ten: String { return RTLocalizationSystem.rtLocalize("ho_va_ten", comment: "")}
    static var dia_chi_email: String { return RTLocalizationSystem.rtLocalize("dia_chi_email", comment: "")}
    static var so_cmnd: String { return RTLocalizationSystem.rtLocalize("so_cmnd", comment: "")}
    static var noi_cap: String { return RTLocalizationSystem.rtLocalize("noi_cap", comment: "")}
    static var ngay_cap: String { return RTLocalizationSystem.rtLocalize("ngay_cap", comment: "")}
    static var so_dien_thoai_unitel: String { return RTLocalizationSystem.rtLocalize("so_dien_thoai_unitel", comment: "")}
    static var ma_otp: String { return RTLocalizationSystem.rtLocalize("ma_otp", comment: "")}
    static var tim_kiem: String { return RTLocalizationSystem.rtLocalize("tim_kiem", comment: "")}
    static var an: String { return RTLocalizationSystem.rtLocalize("an", comment: "")}
    static var bank_account: String { return RTLocalizationSystem.rtLocalize("bank_account", comment: "")}
    static var cash_by_viettel_pay: String { return RTLocalizationSystem.rtLocalize("cash_by_viettel_pay", comment: "")}
    static var phone_number: String { return RTLocalizationSystem.rtLocalize("phone_number", comment: "")}
    static var permanent_address: String { return RTLocalizationSystem.rtLocalize("permanent_address", comment: "")}
    static var tax_code: String { return RTLocalizationSystem.rtLocalize("tax_code", comment: "")}
 
    static var bank_account_number: String { return RTLocalizationSystem.rtLocalize("bank_account_number", comment: "")}
    static var bank: String { return RTLocalizationSystem.rtLocalize("bank", comment: "")}
    static var branch: String { return RTLocalizationSystem.rtLocalize("branch", comment: "")}

    static var payment_watting_approve: String { return RTLocalizationSystem.rtLocalize("payment_watting_approve", comment: "")}
    static var payment_watting_approve_message: String { return RTLocalizationSystem.rtLocalize("payment_watting_approve_message", comment: "")}
   static var manage_Comment: String { return RTLocalizationSystem.rtLocalize("manage_Comment", comment: "")}
   static var wait_approve: String { return RTLocalizationSystem.rtLocalize("wait_approve", comment: "")}
   static var approved_comment: String { return RTLocalizationSystem.rtLocalize("approved_comment", comment: "")}
   static var reject_comment: String { return RTLocalizationSystem.rtLocalize("reject_comment", comment: "")}
   static var all_comment: String { return RTLocalizationSystem.rtLocalize("all_comment", comment: "")}
   static var Video_free: String { return RTLocalizationSystem.rtLocalize("Video_free", comment: "")}
   static var All_comment: String { return RTLocalizationSystem.rtLocalize("All_comment", comment: "")}
   static var Reply_Comment: String { return RTLocalizationSystem.rtLocalize("Reply_Comment", comment: "")}
   static var More_Comment: String { return RTLocalizationSystem.rtLocalize("More_Comment", comment: "")}
   static var require_Name: String { return RTLocalizationSystem.rtLocalize("require_Name", comment: "")}
   static var require_Desc: String { return RTLocalizationSystem.rtLocalize("require_Desc", comment: "")}
   static var max_channel: String { return RTLocalizationSystem.rtLocalize("max_channel", comment: "")}
   static var Creat_Channel: String { return RTLocalizationSystem.rtLocalize("Creat_Channel", comment: "")}
   static var full_Name: String { return RTLocalizationSystem.rtLocalize("full_Name", comment: "")}
   static var add_Channel_Sucess: String { return RTLocalizationSystem.rtLocalize("add_Channel_Sucess", comment: "")}
   static var my_Channel: String { return RTLocalizationSystem.rtLocalize("my_Channel", comment: "")}
   static var channel_not_null: String { return RTLocalizationSystem.rtLocalize("channel_not_null", comment: "")}
   static var user_settings: String { return RTLocalizationSystem.rtLocalize("user_settings", comment: "")}
   static var note: String { return RTLocalizationSystem.rtLocalize("note", comment: "")}
   static var note_avatar: String { return RTLocalizationSystem.rtLocalize("note_avatar", comment: "")}
   static var note_banner: String { return RTLocalizationSystem.rtLocalize("note_banner", comment: "")}
   static var update_Sucess: String { return RTLocalizationSystem.rtLocalize("update_Sucess", comment: "")}
   static var notice: String { return RTLocalizationSystem.rtLocalize("notice", comment: "")}
   static var creat_a_channel: String { return RTLocalizationSystem.rtLocalize("creat_a_channel", comment: "")}
   static var enable_Comment: String { return RTLocalizationSystem.rtLocalize("enable_Comment", comment: "")}
   static var disable_Comment: String { return RTLocalizationSystem.rtLocalize("disable_Comment", comment: "")}
   static var alert_waiting_approve: String { return RTLocalizationSystem.rtLocalize("alert_waiting_approve", comment: "")}
   static var alert_revoke_approve: String { return RTLocalizationSystem.rtLocalize("alert_revoke_approve", comment: "")}
   static var alert_lock_approve: String { return RTLocalizationSystem.rtLocalize("alert_lock_approve", comment: "")}
   static var helloStr: String { return RTLocalizationSystem.rtLocalize("helloStr", comment: "" )}
   static var sucessAcountInfor: String { return RTLocalizationSystem.rtLocalize("sucessAcountInfor", comment: "" )}
   static var chooseChannel: String { return RTLocalizationSystem.rtLocalize("chooseChannel", comment: "" )}
   static var chooseCategory: String { return RTLocalizationSystem.rtLocalize("chooseCategory", comment: "" )}
   static var recent: String { return RTLocalizationSystem.rtLocalize("recent", comment: "" )}
   static var WatchMore: String { return RTLocalizationSystem.rtLocalize("WatchMore", comment: "" )}
   static var More: String { return RTLocalizationSystem.rtLocalize("More", comment: "" )}
   static var Aprrove: String { return RTLocalizationSystem.rtLocalize("Aprrove", comment: "" )}
   static var Reject: String { return RTLocalizationSystem.rtLocalize("Reject", comment: "" )}
   static var maxNameCharacter: String { return RTLocalizationSystem.rtLocalize("maxNameCharacter", comment: "" )}
   static var maxDescCharacter: String { return RTLocalizationSystem.rtLocalize("maxDescCharacter", comment: "" )}
   static var darkMode: String { return RTLocalizationSystem.rtLocalize("darkMode", comment: "" )}
}
